source 'http://rubygems.org'

gem 'rails' , '2.3.5'
gem 'passenger'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'json'
gem 'settingslogic'
gem 'rest-client'
gem 'composite_primary_keys'
gem 'mechanize'
gem 'fastercsv'
gem 'rake'
gem 'rcov'
gem 'rdoc',  '3.8'
