# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "cohort", :id => false, :force => true do |t|
    t.column "cohort_id",    :integer,                  :null => false
    t.column "name",         :string,                   :null => false
    t.column "description",  :string,   :limit => 1000
    t.column "creator",      :integer,                  :null => false
    t.column "date_created", :datetime,                 :null => false
    t.column "voided",       :boolean,                  :null => false
    t.column "voided_by",    :integer
    t.column "date_voided",  :datetime
    t.column "void_reason",  :string
  end

  add_index "cohort", ["creator"], :name => "cohort_creator"
  add_index "cohort", ["voided_by"], :name => "user_who_voided_cohort"

  create_table "cohort_member", :id => false, :force => true do |t|
    t.column "cohort_id",  :integer, :default => 0, :null => false
    t.column "patient_id", :integer, :default => 0, :null => false
  end

  add_index "cohort_member", ["cohort_id"], :name => "cohort"
  add_index "cohort_member", ["patient_id"], :name => "patient"

  create_table "complex_obs", :id => false, :force => true do |t|
    t.column "obs_id",        :integer, :default => 0, :null => false
    t.column "mime_type_id",  :integer, :default => 0, :null => false
    t.column "urn",           :text
    t.column "complex_value", :text
  end

  add_index "complex_obs", ["mime_type_id"], :name => "mime_type_of_content"

  create_table "concept", :id => false, :force => true do |t|
    t.column "concept_id",     :integer,                                   :null => false
    t.column "retired",        :boolean,                :default => false, :null => false
    t.column "short_name",     :string
    t.column "description",    :text
    t.column "form_text",      :text
    t.column "datatype_id",    :integer,                :default => 0,     :null => false
    t.column "class_id",       :integer,                :default => 0,     :null => false
    t.column "is_set",         :boolean,                :default => false, :null => false
    t.column "creator",        :integer,                :default => 0,     :null => false
    t.column "date_created",   :datetime,                                  :null => false
    t.column "default_charge", :integer
    t.column "version",        :string,   :limit => 50
    t.column "changed_by",     :integer
    t.column "date_changed",   :datetime
  end

  add_index "concept", ["class_id"], :name => "concept_classes"
  add_index "concept", ["creator"], :name => "concept_creator"
  add_index "concept", ["datatype_id"], :name => "concept_datatypes"
  add_index "concept", ["changed_by"], :name => "user_who_changed_concept"

  create_table "concept_answer", :id => false, :force => true do |t|
    t.column "concept_answer_id", :integer,                 :null => false
    t.column "concept_id",        :integer,  :default => 0, :null => false
    t.column "answer_concept",    :integer
    t.column "answer_drug",       :integer
    t.column "creator",           :integer,  :default => 0, :null => false
    t.column "date_created",      :datetime,                :null => false
  end

  add_index "concept_answer", ["creator"], :name => "answer_creator"
  add_index "concept_answer", ["answer_concept"], :name => "answer"
  add_index "concept_answer", ["concept_id"], :name => "answers_for_concept"

  create_table "concept_class", :id => false, :force => true do |t|
    t.column "concept_class_id", :integer,                  :null => false
    t.column "name",             :string,   :default => "", :null => false
    t.column "description",      :string,   :default => "", :null => false
    t.column "creator",          :integer,  :default => 0,  :null => false
    t.column "date_created",     :datetime,                 :null => false
  end

  add_index "concept_class", ["creator"], :name => "concept_class_creator"

  create_table "concept_datatype", :id => false, :force => true do |t|
    t.column "concept_datatype_id", :integer,                               :null => false
    t.column "name",                :string,                :default => "", :null => false
    t.column "hl7_abbreviation",    :string,   :limit => 3
    t.column "description",         :string,                :default => "", :null => false
    t.column "creator",             :integer,               :default => 0,  :null => false
    t.column "date_created",        :datetime,                              :null => false
  end

  add_index "concept_datatype", ["creator"], :name => "concept_datatype_creator"

  create_table "concept_derived", :id => false, :force => true do |t|
    t.column "concept_id",     :integer,                  :default => 0, :null => false
    t.column "rule",           :text
    t.column "compile_date",   :datetime
    t.column "compile_status", :string
    t.column "class_name",     :string,   :limit => 1024
  end

  create_table "concept_map", :id => false, :force => true do |t|
    t.column "concept_map_id", :integer,                 :null => false
    t.column "source",         :integer
    t.column "source_id",      :integer
    t.column "comment",        :string
    t.column "creator",        :integer,  :default => 0, :null => false
    t.column "date_created",   :datetime,                :null => false
  end

  add_index "concept_map", ["source"], :name => "map_source"
  add_index "concept_map", ["creator"], :name => "map_creator"

  create_table "concept_name", :id => false, :force => true do |t|
    t.column "concept_id",   :integer,                :default => 0,  :null => false
    t.column "name",         :string,                 :default => "", :null => false
    t.column "short_name",   :string
    t.column "description",  :text,                                   :null => false
    t.column "locale",       :string,   :limit => 50, :default => "", :null => false
    t.column "creator",      :integer,                :default => 0,  :null => false
    t.column "date_created", :datetime,                               :null => false
  end

  add_index "concept_name", ["creator"], :name => "user_who_created_name"
  add_index "concept_name", ["name"], :name => "name_of_concept"
  add_index "concept_name", ["short_name"], :name => "short_name_of_concept"

  create_table "concept_numeric", :id => false, :force => true do |t|
    t.column "concept_id",   :integer,               :default => 0,     :null => false
    t.column "hi_absolute",  :float
    t.column "hi_critical",  :float
    t.column "hi_normal",    :float
    t.column "low_absolute", :float
    t.column "low_critical", :float
    t.column "low_normal",   :float
    t.column "units",        :string,  :limit => 50
    t.column "precise",      :boolean,               :default => false, :null => false
  end

  create_table "concept_proposal", :id => false, :force => true do |t|
    t.column "concept_proposal_id", :integer,                                        :null => false
    t.column "concept_id",          :integer
    t.column "encounter_id",        :integer
    t.column "original_text",       :string,                 :default => "",         :null => false
    t.column "final_text",          :string
    t.column "obs_id",              :integer
    t.column "obs_concept_id",      :integer
    t.column "state",               :string,   :limit => 32, :default => "UNMAPPED", :null => false
    t.column "comments",            :string
    t.column "creator",             :integer,                :default => 0,          :null => false
    t.column "date_created",        :datetime,                                       :null => false
    t.column "changed_by",          :integer
    t.column "date_changed",        :datetime
  end

  add_index "concept_proposal", ["encounter_id"], :name => "encounter_for_proposal"
  add_index "concept_proposal", ["concept_id"], :name => "concept_for_proposal"
  add_index "concept_proposal", ["creator"], :name => "user_who_created_proposal"
  add_index "concept_proposal", ["changed_by"], :name => "user_who_changed_proposal"
  add_index "concept_proposal", ["obs_id"], :name => "proposal_obs_id"
  add_index "concept_proposal", ["obs_concept_id"], :name => "proposal_obs_concept_id"

  create_table "concept_set", :id => false, :force => true do |t|
    t.column "concept_id",   :integer,  :default => 0, :null => false
    t.column "concept_set",  :integer,  :default => 0, :null => false
    t.column "sort_weight",  :float
    t.column "creator",      :integer,  :default => 0, :null => false
    t.column "date_created", :datetime,                :null => false
  end

  add_index "concept_set", ["concept_set"], :name => "has_a"
  add_index "concept_set", ["creator"], :name => "user_who_created"

  create_table "concept_set_derived", :id => false, :force => true do |t|
    t.column "concept_id",  :integer, :default => 0, :null => false
    t.column "concept_set", :integer, :default => 0, :null => false
    t.column "sort_weight", :float
  end

  create_table "concept_source", :id => false, :force => true do |t|
    t.column "concept_source_id", :integer,                                :null => false
    t.column "name",              :string,   :limit => 50, :default => "", :null => false
    t.column "description",       :text,                                   :null => false
    t.column "hl7_code",          :string,   :limit => 50, :default => "", :null => false
    t.column "creator",           :integer,                :default => 0,  :null => false
    t.column "date_created",      :datetime,                               :null => false
    t.column "voided",            :integer,  :limit => 4
    t.column "voided_by",         :integer
    t.column "date_voided",       :datetime
    t.column "void_reason",       :string
  end

  add_index "concept_source", ["creator"], :name => "concept_source_creator"
  add_index "concept_source", ["voided_by"], :name => "user_who_voided_concept_source"

  create_table "concept_state_conversion", :id => false, :force => true do |t|
    t.column "concept_state_conversion_id", :integer,                :null => false
    t.column "concept_id",                  :integer, :default => 0
    t.column "program_workflow_id",         :integer, :default => 0
    t.column "program_workflow_state_id",   :integer, :default => 0
  end

  add_index "concept_state_conversion", ["program_workflow_id", "concept_id"], :name => "unique_workflow_concept_in_conversion", :unique => true
  add_index "concept_state_conversion", ["concept_id"], :name => "triggering_concept"
  add_index "concept_state_conversion", ["program_workflow_id"], :name => "affected_workflow"
  add_index "concept_state_conversion", ["program_workflow_state_id"], :name => "resulting_state"

  create_table "concept_synonym", :id => false, :force => true do |t|
    t.column "concept_id",   :integer,  :default => 0,  :null => false
    t.column "synonym",      :string,   :default => "", :null => false
    t.column "locale",       :string
    t.column "creator",      :integer,  :default => 0,  :null => false
    t.column "date_created", :datetime,                 :null => false
  end

  add_index "concept_synonym", ["concept_id"], :name => "synonym_for"
  add_index "concept_synonym", ["creator"], :name => "synonym_creator"

  create_table "concept_word", :id => false, :force => true do |t|
    t.column "concept_id", :integer,               :default => 0,  :null => false
    t.column "word",       :string,  :limit => 50, :default => "", :null => false
    t.column "synonym",    :string,                :default => "", :null => false
    t.column "locale",     :string,  :limit => 20, :default => "", :null => false
  end

  add_index "concept_word", ["word"], :name => "word_in_concept_name"

  create_table "drug", :id => false, :force => true do |t|
    t.column "drug_id",            :integer,                                   :null => false
    t.column "concept_id",         :integer,                :default => 0,     :null => false
    t.column "name",               :string,   :limit => 50
    t.column "combination",        :boolean,                :default => false, :null => false
    t.column "dosage_form",        :integer
    t.column "dose_strength",      :float
    t.column "maximum_daily_dose", :float
    t.column "minimum_daily_dose", :float
    t.column "route",              :integer
    t.column "units",              :string,   :limit => 50
    t.column "creator",            :integer,                :default => 0,     :null => false
    t.column "date_created",       :datetime,                                  :null => false
    t.column "voided",             :boolean,                :default => false, :null => false
    t.column "voided_by",          :integer
    t.column "date_voided",        :datetime
    t.column "void_reason",        :string
  end

  add_index "drug", ["creator"], :name => "drug_creator"
  add_index "drug", ["concept_id"], :name => "primary_drug_concept"
  add_index "drug", ["dosage_form"], :name => "dosage_form_concept"
  add_index "drug", ["route"], :name => "route_concept"
  add_index "drug", ["voided_by"], :name => "user_who_voided_drug"

  create_table "drug_ingredient", :id => false, :force => true do |t|
    t.column "concept_id",    :integer, :default => 0, :null => false
    t.column "ingredient_id", :integer, :default => 0, :null => false
  end

  add_index "drug_ingredient", ["concept_id"], :name => "combination_drug"

  create_table "drug_order", :id => false, :force => true do |t|
    t.column "order_id",              :integer, :default => 0,     :null => false
    t.column "drug_inventory_id",     :integer, :default => 0
    t.column "dose",                  :float
    t.column "equivalent_daily_dose", :float
    t.column "units",                 :string
    t.column "frequency",             :string
    t.column "prn",                   :boolean, :default => false, :null => false
    t.column "complex",               :boolean, :default => false, :null => false
    t.column "quantity",              :integer
  end

  add_index "drug_order", ["drug_inventory_id"], :name => "inventory_item"

  create_table "encounter", :id => false, :force => true do |t|
    t.column "encounter_id",       :integer,                     :null => false
    t.column "encounter_type",     :integer
    t.column "patient_id",         :integer,  :default => 0,     :null => false
    t.column "provider_id",        :integer,  :default => 0,     :null => false
    t.column "location_id",        :integer,  :default => 0,     :null => false
    t.column "form_id",            :integer
    t.column "encounter_datetime", :datetime,                    :null => false
    t.column "creator",            :integer,  :default => 0,     :null => false
    t.column "date_created",       :datetime,                    :null => false
    t.column "voided",             :boolean,  :default => false, :null => false
    t.column "voided_by",          :integer
    t.column "date_voided",        :datetime
    t.column "void_reason",        :string
  end

  add_index "encounter", ["location_id"], :name => "encounter_location"
  add_index "encounter", ["patient_id"], :name => "encounter_patient"
  add_index "encounter", ["provider_id"], :name => "encounter_provider"
  add_index "encounter", ["encounter_type"], :name => "encounter_type_id"
  add_index "encounter", ["creator"], :name => "encounter_creator"
  add_index "encounter", ["form_id"], :name => "encounter_form"
  add_index "encounter", ["voided_by"], :name => "user_who_voided_encounter"

  create_table "encounter_type", :id => false, :force => true do |t|
    t.column "encounter_type_id", :integer,                                :null => false
    t.column "name",              :string,   :limit => 50, :default => "", :null => false
    t.column "description",       :string,   :limit => 50, :default => "", :null => false
    t.column "creator",           :integer,                :default => 0,  :null => false
    t.column "date_created",      :datetime,                               :null => false
  end

  add_index "encounter_type", ["creator"], :name => "user_who_created_type"

  create_table "field", :id => false, :force => true do |t|
    t.column "field_id",        :integer,                                   :null => false
    t.column "name",            :string,                 :default => "",    :null => false
    t.column "description",     :text
    t.column "field_type",      :integer
    t.column "concept_id",      :integer
    t.column "table_name",      :string,   :limit => 50
    t.column "attribute_name",  :string,   :limit => 50
    t.column "default_value",   :text
    t.column "select_multiple", :boolean,                :default => false, :null => false
    t.column "creator",         :integer,                :default => 0,     :null => false
    t.column "date_created",    :datetime,                                  :null => false
    t.column "changed_by",      :integer
    t.column "date_changed",    :datetime
  end

  add_index "field", ["concept_id"], :name => "concept_for_field"
  add_index "field", ["changed_by"], :name => "user_who_changed_field"
  add_index "field", ["creator"], :name => "user_who_created_field"
  add_index "field", ["field_type"], :name => "type_of_field"

  create_table "field_answer", :id => false, :force => true do |t|
    t.column "field_id",     :integer,  :default => 0, :null => false
    t.column "answer_id",    :integer,  :default => 0, :null => false
    t.column "creator",      :integer,  :default => 0, :null => false
    t.column "date_created", :datetime,                :null => false
  end

  add_index "field_answer", ["field_id"], :name => "answers_for_field"
  add_index "field_answer", ["answer_id"], :name => "field_answer_concept"
  add_index "field_answer", ["creator"], :name => "user_who_created_field_answer"

  create_table "field_type", :id => false, :force => true do |t|
    t.column "field_type_id", :integer,                                   :null => false
    t.column "name",          :string,   :limit => 50
    t.column "description",   :text
    t.column "is_set",        :boolean,                :default => false, :null => false
    t.column "creator",       :integer,                :default => 0,     :null => false
    t.column "date_created",  :datetime,                                  :null => false
  end

  add_index "field_type", ["creator"], :name => "user_who_created_field_type"

  create_table "form", :id => false, :force => true do |t|
    t.column "form_id",        :integer,                                   :null => false
    t.column "name",           :string,                 :default => "",    :null => false
    t.column "version",        :string,   :limit => 50, :default => "",    :null => false
    t.column "build",          :integer
    t.column "published",      :integer,  :limit => 4,  :default => 0,     :null => false
    t.column "description",    :text
    t.column "encounter_type", :integer
    t.column "template",       :text
    t.column "xslt",           :text
    t.column "creator",        :integer,                :default => 0,     :null => false
    t.column "date_created",   :datetime,                                  :null => false
    t.column "changed_by",     :integer
    t.column "date_changed",   :datetime
    t.column "retired",        :boolean,                :default => false, :null => false
    t.column "retired_by",     :integer
    t.column "date_retired",   :datetime
    t.column "retired_reason", :string
  end

  add_index "form", ["creator"], :name => "user_who_created_form"
  add_index "form", ["changed_by"], :name => "user_who_last_changed_form"
  add_index "form", ["retired_by"], :name => "user_who_retired_form"
  add_index "form", ["encounter_type"], :name => "encounter_type"

  create_table "form_field", :id => false, :force => true do |t|
    t.column "form_field_id",     :integer,                               :null => false
    t.column "form_id",           :integer,                :default => 0, :null => false
    t.column "field_id",          :integer,                :default => 0, :null => false
    t.column "field_number",      :integer
    t.column "field_part",        :string,   :limit => 5
    t.column "page_number",       :integer
    t.column "parent_form_field", :integer
    t.column "min_occurs",        :integer
    t.column "max_occurs",        :integer
    t.column "required",          :boolean
    t.column "changed_by",        :integer
    t.column "date_changed",      :datetime
    t.column "creator",           :integer,                :default => 0, :null => false
    t.column "date_created",      :datetime,                              :null => false
    t.column "sort_weight",       :float,    :limit => 11
  end

  add_index "form_field", ["changed_by"], :name => "user_who_last_changed_form_field"
  add_index "form_field", ["field_id"], :name => "field_within_form"
  add_index "form_field", ["form_id"], :name => "form_containing_field"
  add_index "form_field", ["parent_form_field"], :name => "form_field_hierarchy"
  add_index "form_field", ["creator"], :name => "user_who_created_form_field"

  create_table "formentry_error", :id => false, :force => true do |t|
    t.column "formentry_error_id", :integer,                  :null => false
    t.column "form_data",          :text,                     :null => false
    t.column "error",              :string,   :default => "", :null => false
    t.column "error_details",      :text
    t.column "creator",            :integer,  :default => 0,  :null => false
    t.column "date_created",       :datetime,                 :null => false
  end

  add_index "formentry_error", ["creator"], :name => "User who created formentry_error"

  create_table "formentry_xsn", :id => false, :force => true do |t|
    t.column "formentry_xsn_id", :integer,                              :null => false
    t.column "form_id",          :integer,                              :null => false
    t.column "xsn_data",         :binary,                               :null => false
    t.column "creator",          :integer,               :default => 0, :null => false
    t.column "date_created",     :datetime,                             :null => false
    t.column "archived",         :integer,  :limit => 1, :default => 0, :null => false
    t.column "archived_by",      :integer
    t.column "date_archived",    :datetime
  end

  add_index "formentry_xsn", ["creator"], :name => "User who created formentry_xsn"
  add_index "formentry_xsn", ["form_id"], :name => "Form with which this xsn is related"
  add_index "formentry_xsn", ["archived_by"], :name => "User who archived formentry_xsn"

  create_table "global_property", :id => false, :force => true do |t|
    t.column "property",       :string, :default => "", :null => false
    t.column "property_value", :text
    t.column "description",    :text
  end

  create_table "hl7_in_archive", :id => false, :force => true do |t|
    t.column "hl7_in_archive_id", :integer,                 :null => false
    t.column "hl7_source",        :integer,  :default => 0, :null => false
    t.column "hl7_source_key",    :string
    t.column "hl7_data",          :text,                    :null => false
    t.column "date_created",      :datetime,                :null => false
  end

  create_table "hl7_in_error", :id => false, :force => true do |t|
    t.column "hl7_in_error_id", :integer,                  :null => false
    t.column "hl7_source",      :integer,  :default => 0,  :null => false
    t.column "hl7_source_key",  :text
    t.column "hl7_data",        :text,                     :null => false
    t.column "error",           :string,   :default => "", :null => false
    t.column "error_details",   :text
    t.column "date_created",    :datetime,                 :null => false
  end

  create_table "hl7_in_queue", :id => false, :force => true do |t|
    t.column "hl7_in_queue_id", :integer,                 :null => false
    t.column "hl7_source",      :integer,  :default => 0, :null => false
    t.column "hl7_source_key",  :text
    t.column "hl7_data",        :text,                    :null => false
    t.column "state",           :integer,  :default => 0, :null => false
    t.column "date_processed",  :datetime
    t.column "error_msg",       :text
    t.column "date_created",    :datetime
  end

  add_index "hl7_in_queue", ["hl7_source"], :name => "hl7_source"

  create_table "hl7_source", :id => false, :force => true do |t|
    t.column "hl7_source_id", :integer,                  :null => false
    t.column "name",          :string,   :default => "", :null => false
    t.column "description",   :text
    t.column "creator",       :integer,  :default => 0,  :null => false
    t.column "date_created",  :datetime,                 :null => false
  end

  add_index "hl7_source", ["creator"], :name => "creator"

  create_table "location", :id => false, :force => true do |t|
    t.column "location_id",       :integer,                                :null => false
    t.column "name",              :string,                 :default => "", :null => false
    t.column "description",       :string
    t.column "address1",          :string,   :limit => 50
    t.column "address2",          :string,   :limit => 50
    t.column "city_village",      :string,   :limit => 50
    t.column "state_province",    :string,   :limit => 50
    t.column "postal_code",       :string,   :limit => 50
    t.column "country",           :string,   :limit => 50
    t.column "latitude",          :string,   :limit => 50
    t.column "longitude",         :string,   :limit => 50
    t.column "creator",           :integer,                :default => 0,  :null => false
    t.column "date_created",      :datetime,                               :null => false
    t.column "county_district",   :string,   :limit => 50
    t.column "neighborhood_cell", :string,   :limit => 50
    t.column "region",            :string,   :limit => 50
    t.column "subregion",         :string,   :limit => 50
    t.column "township_division", :string,   :limit => 50
  end

  add_index "location", ["creator"], :name => "user_who_created_location"
  add_index "location", ["name"], :name => "name_of_location"

  create_table "mime_type", :id => false, :force => true do |t|
    t.column "mime_type_id", :integer,                               :null => false
    t.column "mime_type",    :string,  :limit => 75, :default => "", :null => false
    t.column "description",  :text
  end

  add_index "mime_type", ["mime_type_id"], :name => "mime_type_id"

  create_table "note", :id => false, :force => true do |t|
    t.column "note_id",      :integer,                :default => 0, :null => false
    t.column "note_type",    :string,   :limit => 50
    t.column "patient_id",   :integer
    t.column "obs_id",       :integer
    t.column "encounter_id", :integer
    t.column "text",         :text,                                  :null => false
    t.column "priority",     :integer
    t.column "parent",       :integer
    t.column "creator",      :integer,                :default => 0, :null => false
    t.column "date_created", :datetime,                              :null => false
    t.column "changed_by",   :integer
    t.column "date_changed", :datetime
  end

  add_index "note", ["patient_id"], :name => "patient_note"
  add_index "note", ["obs_id"], :name => "obs_note"
  add_index "note", ["encounter_id"], :name => "encounter_note"
  add_index "note", ["creator"], :name => "user_who_created_note"
  add_index "note", ["changed_by"], :name => "user_who_changed_note"
  add_index "note", ["parent"], :name => "note_hierarchy"

  create_table "notification_alert", :id => false, :force => true do |t|
    t.column "alert_id",         :integer,                                :null => false
    t.column "user_id",          :integer
    t.column "text",             :string,   :limit => 512,                :null => false
    t.column "satisfied_by_any", :integer,  :limit => 1,   :default => 0, :null => false
    t.column "alert_read",       :integer,  :limit => 1,   :default => 0, :null => false
    t.column "date_to_expire",   :datetime
    t.column "creator",          :integer,                                :null => false
    t.column "date_created",     :datetime,                               :null => false
    t.column "changed_by",       :integer
    t.column "date_changed",     :datetime
  end

  add_index "notification_alert", ["creator"], :name => "alert_creator"
  add_index "notification_alert", ["user_id"], :name => "alert_assigned_to_user"
  add_index "notification_alert", ["changed_by"], :name => "user_who_changed_alert"

  create_table "notification_alert_recipient", :id => false, :force => true do |t|
    t.column "alert_id",     :integer,                               :null => false
    t.column "user_id",      :integer,                               :null => false
    t.column "alert_read",   :integer,   :limit => 1, :default => 0, :null => false
    t.column "date_changed", :timestamp
  end

  add_index "notification_alert_recipient", ["user_id"], :name => "alert_read_by_user"
  add_index "notification_alert_recipient", ["alert_id"], :name => "id_of_alert"

  create_table "notification_template", :id => false, :force => true do |t|
    t.column "template_id", :integer,                               :null => false
    t.column "name",        :string,  :limit => 50
    t.column "template",    :text
    t.column "subject",     :string,  :limit => 100
    t.column "sender",      :string
    t.column "recipients",  :string,  :limit => 512
    t.column "ordinal",     :integer,                :default => 0
  end

  create_table "obs", :id => false, :force => true do |t|
    t.column "obs_id",           :integer,                                  :null => false
    t.column "person_id",        :integer,                                  :null => false
    t.column "concept_id",       :integer,               :default => 0,     :null => false
    t.column "encounter_id",     :integer
    t.column "order_id",         :integer
    t.column "obs_datetime",     :datetime,                                 :null => false
    t.column "location_id",      :integer,               :default => 0,     :null => false
    t.column "obs_group_id",     :integer
    t.column "accession_number", :string
    t.column "value_group_id",   :integer
    t.column "value_boolean",    :boolean
    t.column "value_coded",      :integer
    t.column "value_drug",       :integer
    t.column "value_datetime",   :datetime
    t.column "value_numeric",    :float
    t.column "value_modifier",   :string,   :limit => 2
    t.column "value_text",       :text
    t.column "date_started",     :datetime
    t.column "date_stopped",     :datetime
    t.column "comments",         :string
    t.column "creator",          :integer,               :default => 0,     :null => false
    t.column "date_created",     :datetime,                                 :null => false
    t.column "voided",           :boolean,               :default => false, :null => false
    t.column "voided_by",        :integer
    t.column "date_voided",      :datetime
    t.column "void_reason",      :string
  end

  add_index "obs", ["value_coded"], :name => "answer_concept"
  add_index "obs", ["encounter_id"], :name => "encounter_observations"
  add_index "obs", ["concept_id"], :name => "obs_concept"
  add_index "obs", ["creator"], :name => "obs_enterer"
  add_index "obs", ["location_id"], :name => "obs_location"
  add_index "obs", ["order_id"], :name => "obs_order"
  add_index "obs", ["person_id"], :name => "patient_obs"
  add_index "obs", ["voided_by"], :name => "user_who_voided_obs"
  add_index "obs", ["value_drug"], :name => "answer_concept_drug"

  create_table "order_type", :id => false, :force => true do |t|
    t.column "order_type_id", :integer,                  :null => false
    t.column "name",          :string,   :default => "", :null => false
    t.column "description",   :string,   :default => "", :null => false
    t.column "creator",       :integer,  :default => 0,  :null => false
    t.column "date_created",  :datetime,                 :null => false
  end

  add_index "order_type", ["creator"], :name => "type_created_by"

  create_table "orders", :id => false, :force => true do |t|
    t.column "order_id",            :integer,                     :null => false
    t.column "order_type_id",       :integer,  :default => 0,     :null => false
    t.column "concept_id",          :integer,  :default => 0,     :null => false
    t.column "orderer",             :integer,  :default => 0
    t.column "encounter_id",        :integer
    t.column "instructions",        :text
    t.column "start_date",          :datetime
    t.column "auto_expire_date",    :datetime
    t.column "discontinued",        :boolean,  :default => false, :null => false
    t.column "discontinued_date",   :datetime
    t.column "discontinued_by",     :integer
    t.column "discontinued_reason", :integer
    t.column "creator",             :integer,  :default => 0,     :null => false
    t.column "date_created",        :datetime,                    :null => false
    t.column "voided",              :boolean,  :default => false, :null => false
    t.column "voided_by",           :integer
    t.column "date_voided",         :datetime
    t.column "void_reason",         :string
    t.column "patient_id",          :integer,                     :null => false
  end

  add_index "orders", ["creator"], :name => "order_creator"
  add_index "orders", ["orderer"], :name => "orderer_not_drug"
  add_index "orders", ["encounter_id"], :name => "orders_in_encounter"
  add_index "orders", ["order_type_id"], :name => "type_of_order"
  add_index "orders", ["discontinued_by"], :name => "user_who_discontinued_order"
  add_index "orders", ["voided_by"], :name => "user_who_voided_order"
  add_index "orders", ["discontinued_reason"], :name => "discontinued_because"
  add_index "orders", ["patient_id"], :name => "order_for_patient"

  create_table "patient", :id => false, :force => true do |t|
    t.column "patient_id",   :integer,                     :null => false
    t.column "tribe",        :integer
    t.column "creator",      :integer,  :default => 0,     :null => false
    t.column "date_created", :datetime,                    :null => false
    t.column "changed_by",   :integer
    t.column "date_changed", :datetime
    t.column "voided",       :boolean,  :default => false, :null => false
    t.column "voided_by",    :integer
    t.column "date_voided",  :datetime
    t.column "void_reason",  :string
  end

  add_index "patient", ["tribe"], :name => "belongs_to_tribe"
  add_index "patient", ["creator"], :name => "user_who_created_patient"
  add_index "patient", ["voided_by"], :name => "user_who_voided_patient"
  add_index "patient", ["changed_by"], :name => "user_who_changed_pat"

  create_table "patient_identifier", :id => false, :force => true do |t|
    t.column "patient_id",      :integer,                :default => 0,     :null => false
    t.column "identifier",      :string,   :limit => 50, :default => "",    :null => false
    t.column "identifier_type", :integer,                :default => 0,     :null => false
    t.column "preferred",       :integer,  :limit => 4,  :default => 0,     :null => false
    t.column "location_id",     :integer,                :default => 0,     :null => false
    t.column "creator",         :integer,                :default => 0,     :null => false
    t.column "date_created",    :datetime,                                  :null => false
    t.column "voided",          :boolean,                :default => false, :null => false
    t.column "voided_by",       :integer
    t.column "date_voided",     :datetime
    t.column "void_reason",     :string
  end

  add_index "patient_identifier", ["identifier_type"], :name => "defines_identifier_type"
  add_index "patient_identifier", ["creator"], :name => "identifier_creator"
  add_index "patient_identifier", ["voided_by"], :name => "identifier_voider"
  add_index "patient_identifier", ["location_id"], :name => "identifier_location"
  add_index "patient_identifier", ["identifier"], :name => "identifier_name"

  create_table "patient_identifier_type", :id => false, :force => true do |t|
    t.column "patient_identifier_type_id", :integer,                                   :null => false
    t.column "name",                       :string,   :limit => 50, :default => "",    :null => false
    t.column "description",                :text,                                      :null => false
    t.column "format",                     :string,   :limit => 50
    t.column "check_digit",                :boolean,                :default => false, :null => false
    t.column "creator",                    :integer,                :default => 0,     :null => false
    t.column "date_created",               :datetime,                                  :null => false
    t.column "required",                   :boolean,                :default => false, :null => false
    t.column "format_description",         :string
  end

  add_index "patient_identifier_type", ["creator"], :name => "type_creator"

  create_table "patient_program", :id => false, :force => true do |t|
    t.column "patient_program_id", :integer,                     :null => false
    t.column "patient_id",         :integer,  :default => 0,     :null => false
    t.column "program_id",         :integer,  :default => 0,     :null => false
    t.column "date_enrolled",      :datetime
    t.column "date_completed",     :datetime
    t.column "creator",            :integer,  :default => 0,     :null => false
    t.column "date_created",       :datetime,                    :null => false
    t.column "changed_by",         :integer
    t.column "date_changed",       :datetime
    t.column "voided",             :boolean,  :default => false, :null => false
    t.column "voided_by",          :integer
    t.column "date_voided",        :datetime
    t.column "void_reason",        :string
  end

  add_index "patient_program", ["patient_id"], :name => "patient_in_program"
  add_index "patient_program", ["program_id"], :name => "program_for_patient"
  add_index "patient_program", ["creator"], :name => "patient_program_creator"
  add_index "patient_program", ["changed_by"], :name => "user_who_changed"
  add_index "patient_program", ["voided_by"], :name => "user_who_voided_patient_program"

  create_table "patient_state", :id => false, :force => true do |t|
    t.column "patient_state_id",   :integer,                     :null => false
    t.column "patient_program_id", :integer,  :default => 0,     :null => false
    t.column "state",              :integer,  :default => 0,     :null => false
    t.column "start_date",         :date
    t.column "end_date",           :date
    t.column "creator",            :integer,  :default => 0,     :null => false
    t.column "date_created",       :datetime,                    :null => false
    t.column "changed_by",         :integer
    t.column "date_changed",       :datetime
    t.column "voided",             :boolean,  :default => false, :null => false
    t.column "voided_by",          :integer
    t.column "date_voided",        :datetime
    t.column "void_reason",        :string
  end

  add_index "patient_state", ["state"], :name => "state_for_patient"
  add_index "patient_state", ["patient_program_id"], :name => "patient_program_for_state"
  add_index "patient_state", ["creator"], :name => "patient_state_creator"
  add_index "patient_state", ["changed_by"], :name => "patient_state_changer"
  add_index "patient_state", ["voided_by"], :name => "patient_state_voider"

  create_table "person", :id => false, :force => true do |t|
    t.column "person_id",           :integer,                                   :null => false
    t.column "gender",              :string,   :limit => 50, :default => ""
    t.column "birthdate",           :date
    t.column "birthdate_estimated", :boolean
    t.column "dead",                :integer,  :limit => 1,  :default => 0,     :null => false
    t.column "death_date",          :datetime
    t.column "cause_of_death",      :integer
    t.column "creator",             :integer,                :default => 0,     :null => false
    t.column "date_created",        :datetime,                                  :null => false
    t.column "changed_by",          :integer
    t.column "date_changed",        :datetime
    t.column "voided",              :boolean,                :default => false, :null => false
    t.column "voided_by",           :integer
    t.column "date_voided",         :datetime
    t.column "void_reason",         :string
  end

  add_index "person", ["creator"], :name => "user_who_created_patient"
  add_index "person", ["voided_by"], :name => "user_who_voided_patient"
  add_index "person", ["changed_by"], :name => "user_who_changed_pat"
  add_index "person", ["birthdate"], :name => "person_birthdate"
  add_index "person", ["death_date"], :name => "person_death_date"
  add_index "person", ["cause_of_death"], :name => "person_died_because"

  create_table "person_address", :id => false, :force => true do |t|
    t.column "person_address_id", :integer,                                   :null => false
    t.column "person_id",         :integer
    t.column "preferred",         :boolean,                :default => false, :null => false
    t.column "address1",          :string,   :limit => 50
    t.column "address2",          :string,   :limit => 50
    t.column "city_village",      :string,   :limit => 50
    t.column "state_province",    :string,   :limit => 50
    t.column "postal_code",       :string,   :limit => 50
    t.column "country",           :string,   :limit => 50
    t.column "latitude",          :string,   :limit => 50
    t.column "longitude",         :string,   :limit => 50
    t.column "creator",           :integer,                :default => 0,     :null => false
    t.column "date_created",      :datetime,                                  :null => false
    t.column "voided",            :boolean,                :default => false, :null => false
    t.column "voided_by",         :integer
    t.column "date_voided",       :datetime
    t.column "void_reason",       :string
    t.column "county_district",   :string,   :limit => 50
    t.column "neighborhood_cell", :string,   :limit => 50
    t.column "region",            :string,   :limit => 50
    t.column "subregion",         :string,   :limit => 50
    t.column "township_division", :string,   :limit => 50
  end

  add_index "person_address", ["creator"], :name => "patient_address_creator"
  add_index "person_address", ["person_id"], :name => "patient_addresses"
  add_index "person_address", ["voided_by"], :name => "patient_address_void"

  create_table "person_attribute", :id => false, :force => true do |t|
    t.column "person_attribute_id",      :integer,                                   :null => false
    t.column "person_id",                :integer,                :default => 0,     :null => false
    t.column "value",                    :string,   :limit => 50, :default => "",    :null => false
    t.column "person_attribute_type_id", :integer,                :default => 0,     :null => false
    t.column "creator",                  :integer,                :default => 0,     :null => false
    t.column "date_created",             :datetime,                                  :null => false
    t.column "changed_by",               :integer
    t.column "date_changed",             :datetime
    t.column "voided",                   :boolean,                :default => false, :null => false
    t.column "voided_by",                :integer
    t.column "date_voided",              :datetime
    t.column "void_reason",              :string
  end

  add_index "person_attribute", ["person_id"], :name => "identifies_person"
  add_index "person_attribute", ["person_attribute_type_id"], :name => "defines_attribute_type"
  add_index "person_attribute", ["creator"], :name => "attribute_creator"
  add_index "person_attribute", ["changed_by"], :name => "attribute_changer"
  add_index "person_attribute", ["voided_by"], :name => "attribute_voider"

  create_table "person_attribute_type", :id => false, :force => true do |t|
    t.column "person_attribute_type_id", :integer,                                :null => false
    t.column "name",                     :string,   :limit => 50, :default => "", :null => false
    t.column "description",              :text,                                   :null => false
    t.column "format",                   :string,   :limit => 50
    t.column "foreign_key",              :integer
    t.column "searchable",               :integer,  :limit => 1,  :default => 0,  :null => false
    t.column "creator",                  :integer,                :default => 0,  :null => false
    t.column "date_created",             :datetime,                               :null => false
    t.column "changed_by",               :integer
    t.column "date_changed",             :datetime
  end

  add_index "person_attribute_type", ["name"], :name => "name_of_attribute"
  add_index "person_attribute_type", ["creator"], :name => "type_creator"
  add_index "person_attribute_type", ["changed_by"], :name => "attribute_type_changer"
  add_index "person_attribute_type", ["searchable"], :name => "attribute_is_searchable"

  create_table "person_name", :id => false, :force => true do |t|
    t.column "person_name_id",     :integer,                                   :null => false
    t.column "preferred",          :boolean,                :default => false, :null => false
    t.column "person_id",          :integer
    t.column "prefix",             :string,   :limit => 50
    t.column "given_name",         :string,   :limit => 50
    t.column "middle_name",        :string,   :limit => 50
    t.column "family_name_prefix", :string,   :limit => 50
    t.column "family_name",        :string,   :limit => 50
    t.column "family_name2",       :string,   :limit => 50
    t.column "family_name_suffix", :string,   :limit => 50
    t.column "degree",             :string,   :limit => 50
    t.column "creator",            :integer,                :default => 0,     :null => false
    t.column "date_created",       :datetime,                                  :null => false
    t.column "voided",             :boolean,                :default => false, :null => false
    t.column "voided_by",          :integer
    t.column "date_voided",        :datetime
    t.column "void_reason",        :string
    t.column "changed_by",         :integer
    t.column "date_changed",       :datetime
  end

  add_index "person_name", ["person_id"], :name => "name_for_patient"
  add_index "person_name", ["creator"], :name => "user_who_made_name"
  add_index "person_name", ["voided_by"], :name => "user_who_voided_name"
  add_index "person_name", ["given_name"], :name => "first_name"
  add_index "person_name", ["middle_name"], :name => "middle_name"
  add_index "person_name", ["family_name"], :name => "last_name"

  create_table "privilege", :id => false, :force => true do |t|
    t.column "privilege",   :string, :limit => 50,  :default => "", :null => false
    t.column "description", :string, :limit => 250, :default => "", :null => false
  end

  create_table "program", :id => false, :force => true do |t|
    t.column "program_id",   :integer,                     :null => false
    t.column "concept_id",   :integer,  :default => 0,     :null => false
    t.column "creator",      :integer,  :default => 0,     :null => false
    t.column "date_created", :datetime,                    :null => false
    t.column "changed_by",   :integer
    t.column "date_changed", :datetime
    t.column "voided",       :boolean,  :default => false, :null => false
    t.column "voided_by",    :integer
    t.column "date_voided",  :datetime
    t.column "void_reason",  :string
  end

  add_index "program", ["concept_id"], :name => "program_concept"
  add_index "program", ["creator"], :name => "program_creator"
  add_index "program", ["changed_by"], :name => "user_who_changed_program"
  add_index "program", ["voided_by"], :name => "user_who_voided_program"

  create_table "program_workflow", :id => false, :force => true do |t|
    t.column "program_workflow_id", :integer,                 :null => false
    t.column "program_id",          :integer,  :default => 0, :null => false
    t.column "concept_id",          :integer,  :default => 0, :null => false
    t.column "creator",             :integer,  :default => 0, :null => false
    t.column "date_created",        :datetime,                :null => false
    t.column "voided",              :boolean
    t.column "voided_by",           :integer
    t.column "date_voided",         :datetime
    t.column "void_reason",         :string
  end

  add_index "program_workflow", ["program_id"], :name => "program_for_workflow"
  add_index "program_workflow", ["concept_id"], :name => "workflow_concept"
  add_index "program_workflow", ["creator"], :name => "workflow_creator"
  add_index "program_workflow", ["voided_by"], :name => "workflow_voided_by"

  create_table "program_workflow_state", :id => false, :force => true do |t|
    t.column "program_workflow_state_id", :integer,                     :null => false
    t.column "program_workflow_id",       :integer,  :default => 0,     :null => false
    t.column "concept_id",                :integer,  :default => 0,     :null => false
    t.column "initial",                   :boolean,  :default => false, :null => false
    t.column "terminal",                  :boolean,  :default => false, :null => false
    t.column "creator",                   :integer,  :default => 0,     :null => false
    t.column "date_created",              :datetime,                    :null => false
    t.column "voided",                    :boolean
    t.column "voided_by",                 :integer
    t.column "date_voided",               :datetime
    t.column "void_reason",               :string
  end

  add_index "program_workflow_state", ["program_workflow_id"], :name => "workflow_for_state"
  add_index "program_workflow_state", ["concept_id"], :name => "state_concept"
  add_index "program_workflow_state", ["creator"], :name => "state_creator"
  add_index "program_workflow_state", ["voided_by"], :name => "state_voided_by"

  create_table "relationship", :id => false, :force => true do |t|
    t.column "relationship_id", :integer,                     :null => false
    t.column "person_a",        :integer,                     :null => false
    t.column "relationship",    :integer,  :default => 0,     :null => false
    t.column "person_b",        :integer,                     :null => false
    t.column "creator",         :integer,  :default => 0,     :null => false
    t.column "date_created",    :datetime,                    :null => false
    t.column "voided",          :boolean,  :default => false, :null => false
    t.column "voided_by",       :integer
    t.column "date_voided",     :datetime
    t.column "void_reason",     :string
  end

  add_index "relationship", ["person_a"], :name => "related_person"
  add_index "relationship", ["person_b"], :name => "related_relative"
  add_index "relationship", ["relationship"], :name => "relationship_type"
  add_index "relationship", ["creator"], :name => "relation_creator"
  add_index "relationship", ["voided_by"], :name => "relation_voider"

  create_table "relationship_type", :id => false, :force => true do |t|
    t.column "relationship_type_id", :integer,                                :null => false
    t.column "a_is_to_b",            :string,   :limit => 50,                 :null => false
    t.column "b_is_to_a",            :string,   :limit => 50,                 :null => false
    t.column "preferred",            :integer,  :limit => 1,  :default => 0,  :null => false
    t.column "weight",               :integer,                :default => 0,  :null => false
    t.column "description",          :string,                 :default => "", :null => false
    t.column "creator",              :integer,                :default => 0,  :null => false
    t.column "date_created",         :datetime,                               :null => false
  end

  add_index "relationship_type", ["creator"], :name => "user_who_created_rel"

  create_table "report", :id => false, :force => true do |t|
    t.column "report_id",    :integer,                  :null => false
    t.column "name",         :string,   :default => "", :null => false
    t.column "description",  :text
    t.column "creator",      :integer,  :default => 0,  :null => false
    t.column "date_created", :datetime,                 :null => false
    t.column "changed_by",   :integer
    t.column "date_changed", :datetime
    t.column "voided",       :boolean
    t.column "voided_by",    :integer
    t.column "date_voided",  :datetime
    t.column "void_reason",  :string
  end

  add_index "report", ["creator"], :name => "report_creator"
  add_index "report", ["changed_by"], :name => "user_who_changed_report"
  add_index "report", ["voided_by"], :name => "user_who_voided_report"

  create_table "report_object", :id => false, :force => true do |t|
    t.column "report_object_id",       :integer,                  :null => false
    t.column "name",                   :string,                   :null => false
    t.column "description",            :string,   :limit => 1000
    t.column "report_object_type",     :string,                   :null => false
    t.column "report_object_sub_type", :string,                   :null => false
    t.column "xml_data",               :text
    t.column "creator",                :integer,                  :null => false
    t.column "date_created",           :datetime,                 :null => false
    t.column "changed_by",             :integer
    t.column "date_changed",           :datetime
    t.column "voided",                 :boolean,                  :null => false
    t.column "voided_by",              :integer
    t.column "date_voided",            :datetime
    t.column "void_reason",            :string
  end

  add_index "report_object", ["creator"], :name => "report_object_creator"
  add_index "report_object", ["changed_by"], :name => "user_who_changed_report_object"
  add_index "report_object", ["voided_by"], :name => "user_who_voided_report_object"

  create_table "role", :id => false, :force => true do |t|
    t.column "role",        :string, :limit => 50, :default => "", :null => false
    t.column "description", :string,               :default => "", :null => false
  end

  create_table "role_privilege", :id => false, :force => true do |t|
    t.column "role",      :string, :limit => 50, :default => "", :null => false
    t.column "privilege", :string, :limit => 50, :default => "", :null => false
  end

  add_index "role_privilege", ["role"], :name => "role_privilege"

  create_table "role_role", :id => false, :force => true do |t|
    t.column "parent_role", :string, :limit => 50, :default => "", :null => false
    t.column "child_role",  :string,               :default => "", :null => false
  end

  add_index "role_role", ["child_role"], :name => "inherited_role"

  create_table "scheduler_task_config", :id => false, :force => true do |t|
    t.column "task_config_id",     :integer,                                                     :null => false
    t.column "name",               :string,                                                      :null => false
    t.column "description",        :string,   :limit => 1024
    t.column "schedulable_class",  :text
    t.column "start_time",         :datetime,                                                    :null => false
    t.column "start_time_pattern", :string,   :limit => 50
    t.column "repeat_interval",    :integer,                  :default => 0,                     :null => false
    t.column "start_on_startup",   :integer,  :limit => 1,    :default => 0,                     :null => false
    t.column "started",            :integer,  :limit => 1,    :default => 0,                     :null => false
    t.column "created_by",         :integer,                  :default => 0
    t.column "date_created",       :datetime,                 :default => '2005-01-01 00:00:00'
    t.column "changed_by",         :integer
    t.column "date_changed",       :datetime
  end

  add_index "scheduler_task_config", ["created_by"], :name => "schedule_creator"
  add_index "scheduler_task_config", ["changed_by"], :name => "schedule_changer"

  create_table "scheduler_task_config_property", :id => false, :force => true do |t|
    t.column "task_config_property_id", :integer, :null => false
    t.column "name",                    :string,  :null => false
    t.column "value",                   :text
    t.column "task_config_id",          :integer
  end

  add_index "scheduler_task_config_property", ["task_config_id"], :name => "task_config"

  create_table "tribe", :id => false, :force => true do |t|
    t.column "tribe_id", :integer,                                  :null => false
    t.column "retired",  :boolean,               :default => false, :null => false
    t.column "name",     :string,  :limit => 50, :default => "",    :null => false
  end

  create_table "user_property", :id => false, :force => true do |t|
    t.column "user_id",        :integer,                :default => 0,  :null => false
    t.column "property",       :string,  :limit => 100, :default => "", :null => false
    t.column "property_value", :string,                 :default => "", :null => false
  end

  create_table "user_role", :id => false, :force => true do |t|
    t.column "user_id", :integer,               :default => 0,  :null => false
    t.column "role",    :string,  :limit => 50, :default => "", :null => false
  end

  add_index "user_role", ["user_id"], :name => "user_role"

  create_table "users", :id => false, :force => true do |t|
    t.column "user_id",         :integer,                                   :null => false
    t.column "system_id",       :string,   :limit => 50, :default => "",    :null => false
    t.column "username",        :string,   :limit => 50
    t.column "password",        :string,   :limit => 50
    t.column "salt",            :string,   :limit => 50
    t.column "secret_question", :string
    t.column "secret_answer",   :string
    t.column "creator",         :integer,                :default => 0,     :null => false
    t.column "date_created",    :datetime,                                  :null => false
    t.column "changed_by",      :integer
    t.column "date_changed",    :datetime
    t.column "voided",          :boolean,                :default => false, :null => false
    t.column "voided_by",       :integer
    t.column "date_voided",     :datetime
    t.column "void_reason",     :string
  end

  add_index "users", ["creator"], :name => "user_creator"
  add_index "users", ["changed_by"], :name => "user_who_changed_user"
  add_index "users", ["voided_by"], :name => "user_who_voided_user"

  create_table "weight_for_height", :id => false, :force => true do |t|
    t.column "supinecm",   :float
    t.column "medianwtht", :float
    t.column "sdlowwtht",  :float
    t.column "sdhighwtht", :float
    t.column "sex",        :integer, :limit => 6
    t.column "heightsex",  :string,  :limit => 5
  end

  create_table "weight_for_heights", :id => false, :force => true do |t|
    t.column "supinecm",             :float, :null => false
    t.column "median_weight_height", :float, :null => false
  end

  create_table "weight_height_for_age", :id => false, :force => true do |t|
    t.column "agemths",  :integer, :limit => 6
    t.column "sex",      :integer, :limit => 6
    t.column "medianht", :float
    t.column "sdlowht",  :float
    t.column "sdhighht", :float
    t.column "medianwt", :float
    t.column "sdlowwt",  :float
    t.column "sdhighwt", :float
    t.column "agesex",   :string,  :limit => 4
  end

  create_table "weight_height_for_ages", :id => false, :force => true do |t|
    t.column "age_in_months",        :integer, :limit => 6
    t.column "sex",                  :string,  :limit => 12
    t.column "median_height",        :float
    t.column "standard_low_height",  :float
    t.column "standard_high_height", :float
    t.column "median_weight",        :float
    t.column "standard_low_weight",  :float
    t.column "standard_high_weight", :float
    t.column "age_sex",              :string,  :limit => 4
  end

end
