#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

# smtp_server
puts "Enter the SMTP server (y|n)?"
ans = gets.strip()
if (ans == 'y')
  puts "SMTP server (default: 'localhost'):"
  ans = gets.strip()
  ans = 'localhost' if ans.blank?
  Success.set_global_property('smtp_server', ans)
end  

# smtp_username
puts "Enter the SMTP user name (y|n)?"
ans = gets.strip()
if (ans == 'y')
  puts "SMTP user name (default: 'baobabhealth'):"
  ans = gets.strip()
  ans = 'baobabhealth' if ans.blank?
  Success.set_global_property('smtp_username', ans)
end  

# smtp_password
puts "Enter the SMTP user password (y|n)?"
ans = gets.strip()
if (ans == 'y')
  puts "SMTP password:"
  ans = gets.strip()
  Success.set_global_property('smtp_password', ans)
end  

# clinic hours
puts "Enter the clinic hours (y|n)?"
ans = gets.strip()
if (ans == 'y')
  puts "Clinic hours (default: '7:30am-3:45pm'):"
  ans = gets.strip()
  ans = '7:30am-3:45pm' if ans.blank?
  Success.clinic_hours = ans
end  

# clinic breaks
puts "Enter the clinic breaks (y|n)?"
ans = gets.strip()
if (ans == 'y')
  puts "Clinic breaks (default: '12:30pm-1:00pm,1:00pm-1:15pm'):"
  ans = gets.strip()
  ans = '12:30pm-1:00pm,1:00pm-1:15pm' if ans.blank?
  Success.clinic_breaks = ans
end  

# current health center
puts "Enter the current health center (y|n)?"
ans = gets.strip()
if (ans == 'y')
  default = Location.find_by_name("Neno District Hospital").id rescue nil
  puts "Current health center (default: '#{default}'):"
  ans = gets.strip()
  ans = default if ans.blank?
  Success.set_global_property("current_health_center_id", ans)
end  


puts "To finish setting up, please ensure that your deploy user is running the following cron task:"
puts ""
puts "* * * * mon-fri #{File.dirname(__FILE__)}/script/runner  -e production 'Success.verify'"
puts ""
puts "Done."